# Generated by Django 3.2.15 on 2022-11-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
