# Generated by Django 3.2.15 on 2022-10-12 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_beerstyle_snacktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftBeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('abv', models.PositiveSmallIntegerField()),
                ('og', models.PositiveSmallIntegerField()),
                ('ibu', models.PositiveSmallIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
                ('beer_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.beerstyle')),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brewery')),
            ],
        ),
    ]
