# Generated by Django 3.2.15 on 2022-10-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_draftbeer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DraftBeer',
            new_name='Beer',
        ),
    ]
