# Generated by Django 3.2.15 on 2022-10-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_draftbeer_beer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.beer')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.beervolume')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='volume',
            field=models.ManyToManyField(through='shop.Options', to='shop.BeerVolume'),
        ),
    ]
