# Generated by Django 3.2.15 on 2022-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20221012_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='beervolume',
            name='name',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
