# Generated by Django 3.2.15 on 2022-10-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_beervolume_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='price',
        ),
    ]
