# Generated by Django 3.2.15 on 2022-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_beer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
