# Generated by Django 3.2.15 on 2022-10-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20221016_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.snacktype'),
        ),
        migrations.AlterField(
            model_name='snacktype',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
