# Generated by Django 3.2.15 on 2022-10-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20221016_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='beer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.beertype'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.beerstyle'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brewery'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beertype',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
