# Generated by Django 3.2.15 on 2022-10-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_beertype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerstyle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='beertype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
