# Generated by Django 3.2.15 on 2022-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20221018_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
