# Generated by Django 3.2.15 on 2022-10-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_snacktype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='price',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.RemoveField(
            model_name='beer',
            name='volume',
        ),
        migrations.AddField(
            model_name='beer',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.beervolume'),
        ),
        migrations.AlterField(
            model_name='beervolume',
            name='name',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
