# Generated by Django 3.2.15 on 2022-10-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20221024_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='price',
            new_name='price_per_05',
        ),
        migrations.RenameField(
            model_name='snack',
            old_name='price',
            new_name='price_per_100g',
        ),
        migrations.AddField(
            model_name='snack',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
