# Generated by Django 3.2.15 on 2022-10-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20221024_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
