# Generated by Django 3.2.15 on 2022-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_snack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
