# Generated by Django 3.2.15 on 2022-11-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0002_alter_snack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
